{
  "name": "DOCS",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": {
    "build-docs": {
      "runs-on": "ubuntu-24.04",
      "env": {
        "OS": "ubuntu-24.04",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin/2.5.10"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "cl-telegram-bot-docs",
            "dynamic-space-size": "4gb",
            "cache": "true"
          }
        },
        {
          "name": "Install PlantUML",
          "run": "sudo apt-get install -y plantuml",
          "shell": "bash"
        },
        {
          "name": "Update PlantUML",
          "run": "sudo curl --output /usr/share/plantuml/plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2024.8/plantuml-mit-1.2024.8.jar",
          "shell": "bash"
        },
        {
          "name": "Build Docs",
          "uses": "40ants/build-docs@v1",
          "with": {
            "asdf-system": "cl-telegram-bot-docs",
            "error-on-warnings": true
          }
        }
      ]
    }
  }
}